version: '3'
services:
    web:
        build: .
        container_name: kib-frontend
        command: yarn start
        volumes:
            - .:/app
        ports: 
            - 3000:3000
        